apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        env:
          - name: LDAP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: ldap_password
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: host
        image: nginx
